### ISSUE TITLE
Certains paramètres globaux d'Openfisca sont redéfinis dans parameters.xml

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-paris#1]
On trouve dans les paramètres de cette extension : 

``` xml
  <CODE code="charges_forf_pers_isol" description="Charges forfaitaire de la CAF pour une personne isolée" format="float" type="monetary">

  <CODE code="charges_forf_coloc" description="Charges forfaitaire de la CAF en colocation" format="float" type="monetary">

  <CODE code="charges_forf_couple_ss_enf" description="Charges forfaitaire de la CAF pour un couple sans enfant" format="float" type="monetary">

  <CODE code="charges_forf_couple_enf" description="Charges forfaitaire de la CAF pour un couple avec enfant" format="float" type="monetary">

  <CODE code="smic_net_mensuel" description="Montant du smic net mensuel" format="float" type="monetary">
```

Ce sont des paramètres de la législation française, pas de Paris. Pour éviter des redondances, utiliser les [paramètres globaux](http://legislation.openfisca.fr/parameters).

> Pour le moment c'est un peu difficile à utiliser mais promis on va améliorer ça ;)

**Comment by fpagnoux** [comment]
@kinta95, d'où vient le chiffre de 1150 pour le SMIC mensuel net ? En général, dans les autres prestations, on utilise souvent le smic horaire brut car c'est lui qui est définit légalement. Est-ce que ce chiffre est une approximation propre à la mairie de Paris ? Est-ce qu'il y a une formule pour le calculer ?
Merci !

**Comment by guillett** [comment]
@kinta95, as-tu des informations complémentaires relatives aux interrogations de @fpagnoux ?
Merci d'avance.

**Comment by kinta95** [comment]
Quels sont les interrogations de @fpagnoux<https://github.com/fpagnoux> ?

De : Thomas Guillet [mailto:notifications@github.com]
Envoyé : vendredi 28 juillet 2017 10:17
À : sgmap/openfisca-paris <openfisca-paris@noreply.github.com>
Cc : Kinta MENDY <kinta.mendy@implicit.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sgmap/openfisca-paris] Certains paramètres globaux d'Openfisca sont redéfinis dans parameters.xml (#1)


@kinta95<https://github.com/kinta95>, as-tu des informations complémentaires relatives aux interrogations de @fpagnoux<https://github.com/fpagnoux> ?
Merci d'avance.

**Comment by kinta95** [comment]
@fpagnoux : Le chiffre 1150, c'est la mairie de Paris qui me l'a donné. Veux tu que je mette votre variable du smic ?

**Comment by guillett** [comment]
`charges_forf_pers_isol`, `charges_forf_coloc`, `charges_forf_couple_ss_enf` et `charges_forf_couple_enf` ne sont plus utilisés, les paramètres d'OpenFisca-France ont du être utilisés à la place.

En revanche, `smic_net_mensuel` est utilisé. La valeur sur SMIC a évolué en France depuis le 1/1/16 mais la valeur de `smic_net_mensuel` n'a pas été modifiée. Est-ce normal ? ou bien est-ce l'occasion de voir si le SMIC mensuel net peut-être facilement obtenu à partir du SMIC horaire brut officiellement défini.

**Comment by guillett** [comment]
On n'a plus de contexte et en 4 ans ça n'a pas été vu comme un problème. Je ferme.
