### ISSUE TITLE
Mettre en // le code avec la législation locale

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-paris#71]
Aujourd'hui le code est compliqué et _loin_ de la source de vérité qu'est le [règlement municipal](https://github.com/betagouv/openfisca-paris/files/2880306/Reglement.Municipal.au.1er.juin.2018.pdf)
 et son [annexe](https://github.com/betagouv/openfisca-paris/files/2880291/Annexe.au.1er.janvier.2019.pdf).

Cette complexité est délétère car elle rend difficile la validation et la mise à jour des formules et la mise à jour des barèmes.

C'est une opportunité pour
- rapprocher la structure de l'extension (fichiers, dossiers et sous-dossiers) à celle de la législation (Titres, chapitres).
- rapprocher les variables et leurs formules aux articles
- rapprocher les barèmes et les valeurs présentées dans l'annexe.

Un objectif serait l'autonomisation des équipes de Paris dans la mise à jour des barèmes (pas des formules mais des paramètres [pour le moment :smile: ])

**Comment by ManonLger** [comment]
https://github.com/betagouv/openfisca-paris/pull/72

**Comment by ManonLger** [comment]
https://github.com/betagouv/openfisca-paris/pull/73

**Comment by ManonLger** [comment]
TODO: Clarifier la signification de "cumul" avec la CMU-C
"Le Complément Santé Paris n’est cumulable avec la Couverture Maladie Universelle Complémentaire ou l’Aide à la Complémentaire Santé que dans la limite du plafond fixé par le Conseil de Paris et précisé en annexe II 1.2. a.2"
Par défaut, on ne prend pas en compte cette remarque.

**Comment by ManonLger** [comment]
TODO: Voir comment on veut prendre en compte les "dispositions particulières".
Par exemple article II.1.2.d, page 17.
Dans une première version, on ne les prend pas en compte.

**Comment by ManonLger** [comment]
Refactorise la base ressources (valable pour toutes les aides / tous les publics) :-1:  https://github.com/betagouv/openfisca-paris/pull/80

**Comment by ManonLger** [comment]
Personnes âgées > Paris Logement : https://github.com/betagouv/openfisca-paris/pull/81

**Comment by ManonLger** [comment]
Personnes âgées > Pass Navigo
Personnes handicapées > Pass Navigo
https://github.com/betagouv/openfisca-paris/pull/86

**Comment by ManonLger** [comment]
Familles > Paris Forfait Familles : https://github.com/betagouv/openfisca-paris/pull/87

**Comment by ManonLger** [comment]
Familles > Paris Energie Familles : https://github.com/betagouv/openfisca-paris/pull/88

**Comment by ManonLger** [comment]
Personnes handicapées > Complément Santé Paris : https://github.com/betagouv/openfisca-paris/pull/92

**Comment by ManonLger** [comment]
Reste à faire :
+ Paris Logement pour les personnes handicapées
+ Paris Logement pour les familles
+ clarification des variables liées aux familles (aujd dans `paris.py`)
+ tests unitaires de Paris Solidarité

**Comment by guillett** [comment]
Il faut un minimum d'engagement de la ville de Paris pour que cela ait un sens. À voir si on arrive à monter une expérimentation avec le CASVP.
