### ISSUE TITLE
Calcul du SMIC net mensuel

### ISSUE THREAD

**Issue by ManonLger** [openfisca/openfisca-paris#90]
Aujourd'hui, on a besoin de calculer le SMIC net mensuel, notamment pour Paris Logement : https://github.com/betagouv/openfisca-paris/tree/master/openfisca_paris/personnes_agees/paris_logement.py

Dans l'attente de connaître la formule utilisée par la Ville de Paris, on effectue un produit en croix à partir des valeurs données par : https://www.service-public.fr/particuliers/vosdroits/F2300
`smic_net_mensuel = 7.94 / 10.03 * smic_brut_mensuel`

Il faudrait historiser les paramètres de ce calcul.
Et peut-être le mettre dans `openfisca-france`, car la même manip est faite sur `openfisca-france-local` : https://github.com/betagouv/openfisca-france-local/tree/master/openfisca_france_local/communes/alfortville/noel_enfants.py

**Comment by ManonLger** [comment]
En fait un paramètre a déjà été créé ici : https://github.com/betagouv/openfisca-paris/blob/master/openfisca_paris/parameters/paris/smic_net_mensuel.yaml
Il faudrait probablement l'intégrer à `openfisca-france`.

**Comment by guillett** [comment]
Ah, j'ai du mal à faire cette PR en y voyant ta tête et en repensant à ton engagement sur mes-aides.gouv.fr @ManonLger ... J'espère qu'on pourra à nouveau donner le soin adéquat à cette base de code mais nous ne pouvons pas tout faire nous même, nous seul·e·s. En attendant et espérant que la situation soit plus favorable à un moment donné, je ferme.
